### ISSUE TITLE
Licenseについて

### ISSUE THREAD

**Issue by mapconcierge** [amx-project/0#10]
[license.pdf](https://github.com/amx-project/0/files/10477542/license.pdf)

<img width="668" alt="スクリーンショット 2023-01-23 16 22 32" src="https://user-images.githubusercontent.com/416977/213986376-22a6324e-ad53-45d4-8391-5070d3b74c8a.png">

<img width="676" alt="スクリーンショット 2023-01-23 16 22 36" src="https://user-images.githubusercontent.com/416977/213986373-cf31c304-afab-4646-b7ba-c1b30be08272.png">

**Comment by mapconcierge** [comment]
# 政府標準利用規約準拠について

<img width="674" alt="スクリーンショット 2023-01-23 16 23 41" src="https://user-images.githubusercontent.com/416977/213986511-2e34ca90-74ec-4d68-a9ff-89fd8d0feef9.png">

**Comment by taisukef** [comment]
https://www.moj.go.jp/MINJI/minji05_00494.html
> ３　公開される地図データは、どのような目的で利用してもよいのですか。
>　登記所備付地図データ利用規約に抵触（例：法令に違反、不正目的の利用など）しない範囲で、自由に利用することができます。
>　Ｇ空間情報センターのホームページから地図データをダウンロードするときに、利用規約を確認し、これに同意いただくこととなっています。
ここを読むとほぼオープンデータ

ただ、G空間情報センターの利用規約を確認するとオープンデータではないと読めますね
https://github.com/amx-project/0/issues/1#issuecomment-1401411008

**Comment by nyampire** [comment]
2) 利用の制限
3) 禁止事項

が入っているので、政府標準利用規約には準拠していませんし、オープンデータとは呼べないですね。

**Comment by taisukef** [comment]
ですね
まだ、範囲限定で自由と書いてあるのでまだ利用できる可能性がありますが、G空間情報センターの利用規約は、完全に使えない表記でした

> （１）利用者は本サイトで提供するコンテンツをいかなる目的であれ無断での転載，複製，送信，翻訳・翻案，改変・追加などの一切の行為を禁止いたします。
https://front.geospatial.jp/about/

**Comment by nyampire** [comment]
いいえ、その部分（5条(1)）は、「コンテンツに個別規約がある場合は、個別規約でオーバーライドね」という文言（1条(2)）がありますので、問題にならないです。

> （２）Ｇ空間情報センターで提供しているコンテンツは，本規約以外に，別途，情報提供者により利用規約や注意事項等（以下，「データ利用規約等」という）を定めている場合があります。コンテンツをご利用の際には，これらのデータ利用規約等に従っていただきます。

**Comment by taisukef** [comment]
ありがとうございます
すまません、こちらに表記ありました！
https://www.geospatial.jp/ckan/dataset/houmusyouchizu-2022-1-895

**Comment by hfu** [comment]
- #16
