### ISSUE TITLE
FlatGeobuf の閲覧サイトを作る

### ISSUE THREAD

**Issue by hfu** [amx-project/0#12]
https://github.com/optgeo/flat47-r2ka と同様な形で FlatGeobuf の閲覧サイトを作ると、とりあえず一つの最短経路を辿ったということになると思います。

**Comment by wata909** [comment]
以下のフォーマットに流し込むバージョンについては、私の方でやろうかなと思います。
ただ，任意座標の場合は，外した方がいいですよね。それをどうやって効率的に抽出するのかが，面倒だなと思っています。

https://habs.rad.naro.go.jp/spatial_data/fudepoly47/

**Comment by wata909** [comment]
以下のスクリプトで、任意座標系とそ例外の分類を実施。
ただし、なぜか`shutil.copy`ができない。VScode でやっているからかしら?

```Python
import os
import shutil

src_folder = "data"
dst_folder1 = "ninni"
dst_folder2 = "wgs84"

for root, dirs, files in os.walk(src_folder):
    for file in files:
        if file.endswith(".geojson"):
            file_path = os.path.join(root, file)
            with open(file_path, encoding='utf-8') as f:
                if "任意座標系" in f.read():
                    shutil.copy(file_path, dst_folder1)
                else:
                    shutil.copy(file_path, dst_folder2)
`

**Comment by hfu** [comment]
https://github.com/amx-project/a で全国分のベクトルタイル変換を進める中で、xml ファイルごとの fgb 変換だと割と全体像が見えにくいと感じるに至ったので、本件は凍結気味のクローズとします。
