### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by mapconcierge** [amx-project/0#14]
# Master-Swordsmith-Goro-Masamune-Ukiyo-e

[Master-Swordsmith-Goro-Masamune-Ukiyo-e.png](https://commons.wikimedia.org/wiki/File:Master-Swordsmith-Goro-Masamune-Ukiyo-e.png)

![7A12D905-788A-4C08-8C63-0D9D212BCF78](https://user-images.githubusercontent.com/416977/214225195-ce28d8b0-02d3-4db9-8400-170a74718302.png)

# Katana Muramasa

![E6202269-6819-4CD9-A3B9-9154759AECBE](https://user-images.githubusercontent.com/416977/214224396-1641ca02-c7f5-4dc7-9d4e-380fe4983312.jpeg)

https://commons.wikimedia.org/wiki/File:Katana_Muramasa.JPG

**Comment by hfu** [comment]
- #16
