### ISSUE TITLE
リリース一週間記念 amx-a リリース

### ISSUE THREAD

**Issue by hfu** [amx-project/0#19]
## 作業リスト
1. [x] できるところまで PMTiles を生産する
2. [x] a.pmtiles のミラーを行う
3. [x] ミラーを参照し、地理院最適化ベクトルタイルを背景にする形のデモサイトを作る
4. [x] 上記 3. のデモサイトをリリースする

## ミラーの要領
ミラー要領はシンプルで、 curl -O https://x.optgeo.org/a.pmtiles を予定しています。これをウェブサーバにあげていただければミラーは終了となると思っています。現在表示しているもので 1.9GB なので、全国展開完了後を想定すると、ざっくり 20GB 程度ご用意いただければ十分と思っています。ミラーの URL については、ドキュメントで紹介させていただければと思います

## 位置付け案
法務省地図XMLアダプトプロジェクト amx-project への国連オープンGISイニシアティブDWG7スマートマップの貢献として、地図XMLのPMTilesベクトルタイル変換をした。

※ 追記大歓迎。乗り合わせをして、努力を結集しましょう。

もちろん、 @mapconcierge チームの kuwanauchi なしには amx-a のリリースはありませんでした。適宜、位置付けを整理させていただければと思っています。

**Comment by hfu** [comment]
## 現状
ベクトルタイルに変換できているデータのうち、99%のデータはすごく綺麗に決まっていて、1%のエラーデータが見た目目立ってしまうという状況であるように見えます。綺麗に決まっているデータはとてもかっこいいので、もしよろしければ見てあげてください。

https://protomaps.github.io/PMTiles/?url=https%3A%2F%2Fx.optgeo.org%2Fa.pmtiles#map=5.04/40.67/140.82

**Comment by hfu** [comment]
デモサイトは https://github.com/amx-project/a で実装したということにします。

**Comment by wata909** [comment]
https://habs.rad.naro.go.jp/spatial_data/amx/a.pmtiles
で、随時ミラーします。

**Comment by hfu** [comment]
ありがとうございます！本件クローズとします。
