### ISSUE TITLE
地図XMLの形式について

### ISSUE THREAD

**Issue by hfu** [amx-project/0#2]
地図XMLの形式について、情報共有と議論のためのイシューです。

**Comment by hfu** [comment]
法務省フォーマット及び地図フォーマットの情報が https://www.moj.go.jp/MINJI/minji05_00171.html にあるようです。

**Comment by smellman** [comment]
XMLはスキーマレスなフォーマット(つまりはOSM)ではすごく有効。

**Comment by office-shirado** [comment]
https://www.moj.go.jp/MINJI/minji05_00171.html

地図XMLの仕様書です。

私はCADのオプションでshapeにしてからＧＩＳに入れてます。

また、地図XMLを作成し納品もしています。

**Comment by hfu** [comment]
「法務省フォーマット」の方は、下図を見ると一発でわかる通り、固定長フォーマットのようです。

![法務省フォーマット](https://user-images.githubusercontent.com/18297/213729226-55ae462e-693b-452f-8477-edde84f0e7b6.jpg)

こちらをスキップして、「地図フォーマット」を分析していくと良さそうですね。

**Comment by office-shirado** [comment]
法務者フォーマット：古い
地図XML：現在主流

ですね。

**Comment by smellman** [comment]
GM_Curve これがあるの渋い

**Comment by hfu** [comment]
任意座標系ありに要注意ですね。任意座標系のものはとりあえず飛ばしつつ、平面直角座標系のものを経緯度にして PMTiles にでも変換してみることができたらいいなと思っています。

まずは筆界線のみを変換してみて調子を見ながら他も変換していくアプローチをとってみたいと思いました。

**Comment by office-shirado** [comment]
![image](https://user-images.githubusercontent.com/10629384/213732034-d2c5288a-a24b-4f71-b929-939f5c2f3349.png)

座標系のタグで判別できますw

**Comment by hfu** [comment]
共有ありがとうございます！

私だったら、これをXML処理系で上品に扱わず、割り切って正規表現でフィルタして必要なところだけを切り出していきそうです。

**Comment by office-shirado** [comment]
ちなみに、ドーナツ地は、往復する線を「未描画線」で処理し、ドーナツ地っぽく見せてます。

あと、邪魔なのが「地区外-＊＊＊」という形状ですね。

**Comment by hfu** [comment]
一般的な「地図」のイメージは、これですね。

![ 2023-01-21 0 28 05](https://user-images.githubusercontent.com/18297/213736177-bfe302c2-6016-4bcc-bd9e-32c8a0bbd4f5.jpg)

Source: https://www.moj.go.jp/content/001376880.pdf

**Comment by hfu** [comment]
G空間情報センターが順次地図XMLをGeoJSONに変換したりもされるようです。

**Comment by office-shirado** [comment]
１４条１項地図と１４条４項地図があります。

１４条１項地図が公共座標、４項地図が任意座標というわけでもありません。。。

属性に分類を入れてあげると丁寧かと思います。

**Comment by office-shirado** [comment]
とりあえずは、公共座標のものは、ＧＩＳに使えるという大雑把な分け方で良いかと。

**Comment by office-shirado** [comment]
特殊なものとして、、、
・筆界未定地
・V地番、W地番、X地番、Y地番
・地区外
・別図
などがあります😄

**Comment by kt-kitayama** [comment]
ArcGISをお使いでしたら、とりあえず何も考えずに読めます。
https://blog.esrij.com/2015/09/10/xml-c617/

**Comment by taisukef** [comment]
JavaScriptで試しにJSON化してみました
https://github.com/amx-project/xml2json-js

**Comment by taisukef** [comment]
試しにJSON化したもの、任意座標系でした
緯度経度に変換不可能ってことでしょうか？

**Comment by tosseto** [comment]
任意座標系の場合は，参考になるベース地図や航空写真などを元に幾何補正（通常，GISソフトウェアで手動で行う場合が多そう）するのが一般的かなと思います。そういった意味で，任意座標系の地域と座標系が定義されている地域のリストがあると便利かもしれませんね。

**Comment by taisukef** [comment]
なるほど、他の地図と合わせて使う必要があるんですね
まだまだやることありますねっ

**Comment by hfu** [comment]
- #16
