### ISSUE TITLE
平面直角座標系、JGD 2000/JGD 2011 の取り扱い

### ISSUE THREAD

**Issue by hfu** [amx-project/0#3]
[地図XMLの仕様書](https://www.moj.go.jp/content/000116464.pdf) によれば、

> 測地系は日本測地系2000（JGD2000）又は日本測地系2011（JGD2011）

とのこと。あなたなら、この仕様をどう扱いますか。

**Comment by hfu** [comment]
私なら、経緯度に直す場合、**JGD2000 も JGD2011 もそのまま通過** という発想で、素直にそのまま変換しそうです。

**Comment by office-shirado** [comment]
東日本大震災で私のところですと一部変換パラメータが公開されていないことから、測地成果2011に変換できていない公図があります。

それなりでよければ２mほど東にずらして処理します。

**Comment by office-shirado** [comment]
それと、leafletで、平面直角座標系のまま乗せたりもしたことがあります。

**Comment by fzeeplus** [comment]
関西では2000と2011は影響がなかった為、同じですので、仕様でそのように書いているのだと理解しています。
現在でも、そのような理由で2000変換している測量者が多いことと既存成果が2000である場合原因としてもあります。

**Comment by hfu** [comment]
- #16
