### ISSUE TITLE
2023-02-25 FOSS4G Hokkaido mini #01 でのLT

### ISSUE THREAD

**Issue by wata909** [amx-project/0#9]
FOSS4G Hokkaido mini #01 に参加予定なのですが、こちらのプロジェクトについてLTで紹介してもよろしいでしょうか？

https://foss4ghkdmini01.peatix.com/view

（ラベルは、助けて、要アサインでいいのかしら？）

**Comment by hfu** [comment]
ぜひ、紹介していただければと思います。 @wata909 をアサインさせていただき、ラベルもいい感じに編集しておきますね！

**Comment by wata909** [comment]
承知しました！　申し込みは完了したので、いったんcloseします！
